FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o lucky .

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /app/lucky .
EXPOSE 8081
ENTRYPOINT ["./lucky"]
